name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'trueme-app/**'

  pull_request:
    branches:
      - main
    paths:
      - 'trueme-app/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: trueme-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React Application
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} \
            .

      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}