name: Frontend CI

on:
  push:
    branches:
      - main
    paths:
      - 'trueme-app/**'

  pull_request:
    branches:
      - main
    paths:
      - 'trueme-app/**'

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: trueme-app

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build React Application
        run: npm run build